# Generated by Django 4.1.7 on 2023-03-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Id_Adm', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('Id_Pel', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Alamat', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('Id_Tran', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tgl_Tran', models.DateField()),
                ('Jumlah_Uang', models.IntegerField()),
                ('Id_Pes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('Id_Pes', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Jumlah', models.IntegerField()),
                ('Tgl_pes', models.DateField()),
                ('Id_ADM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin')),
                ('Id_Pel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pelanggan')),
                ('Id_Tran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transaksi')),
            ],
        ),
    ]
