# Generated by Django 4.1.7 on 2023-04-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pesanan_tgl_pes_alter_transaksi_tgl_tran'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='Kembalian',
            field=models.IntegerField(null=True),
        ),
    ]
