# Generated by Django 4.1.7 on 2023-04-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaksi_kembalian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='Id_Pel',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='Id_Pes',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='Id_Tran',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
